src/Entity/Annonce.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\AnnonceRepository;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: AnnonceRepository::class)]
class Annonce
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    #[Assert\NotBlank()]
    #[Assert\Length(min:2,max:100)]
    private ?string $titre = null;

    #[ORM\Column(length: 100)]
    #[Assert\NotBlank()]
    #[Assert\Length(min:2,max:100)]
    private ?string $category = null;

    #[ORM\Column(length: 100)]
    #[Assert\NotBlank()]
    #[Assert\Length(min:2,max:100)]
    private ?string $type = null;

    #[ORM\Column(type: Types::TEXT)]
     #[Assert\NotBlank()]
    #[Assert\Length(min:5)]
    private ?string $description = null;

    #[ORM\Column]
      #[Assert\NotNull()]
    #[Assert\Positive()]
    #[Assert\GreaterThan(10)]
    private ?float $surface = null;

    #[ORM\Column]
     #[Assert\NotNull()]
    #[Assert\Positive()]
    private ?int $number_rooms = null;

    #[ORM\Column]
     #[Assert\NotNull()]
    #[Assert\Positive()]
    private ?int $number_bathrooms = null;

    #[ORM\Column]
     #[Assert\NotNull()]
    #[Assert\Positive()]
    private ?int $number_stages = null;

    #[ORM\Column]
    #[Assert\NotNull()]
    #[Assert\Positive()]
    private ?int $numero_stage = null;

    #[ORM\Column]
     #[Assert\NotNull()]
    #[Assert\Positive()]
    private ?int $number_parkings = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\NotNull()]
    private ?\DateTimeInterface $date_construire = null;

    #[ORM\Column]
     #[Assert\NotNull()]
    #[Assert\Positive()]
    #[Assert\GreaterThan(1)]
    private ?float $price = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank()]
    #[Assert\File()]
    private ?string $media = null;

    #[ORM\Column]
    #[Assert\NotNull()]
    private ?DateTimeImmutable $createdAt = null;

      public function __construct()
    {
$this->createdAt = new DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?float
    {
        return $this->surface;
    }

    public function setSurface(float $surface): static
    {
        $this->surface = $surface;

        return $this;
    }

    public function getNumberRooms(): ?int
    {
        return $this->number_rooms;
    }

    public function setNumberRooms(int $number_rooms): static
    {
        $this->number_rooms = $number_rooms;

        return $this;
    }

    public function getNumberBathrooms(): ?int
    {
        return $this->number_bathrooms;
    }

    public function setNumberBathrooms(int $number_bathrooms): static
    {
        $this->number_bathrooms = $number_bathrooms;

        return $this;
    }

    public function getNumberStages(): ?int
    {
        return $this->number_stages;
    }

    public function setNumberStages(int $number_stages): static
    {
        $this->number_stages = $number_stages;

        return $this;
    }

    public function getNumeroStage(): ?int
    {
        return $this->numero_stage;
    }

    public function setNumeroStage(int $numero_stage): static
    {
        $this->numero_stage = $numero_stage;

        return $this;
    }

    public function getNumberParkings(): ?int
    {
        return $this->number_parkings;
    }

    public function setNumberParkings(int $number_parkings): static
    {
        $this->number_parkings = $number_parkings;

        return $this;
    }

    public function getDateConstruire(): ?\DateTimeInterface
    {
        return $this->date_construire;
    }

    public function setDateConstruire(\DateTimeInterface $date_construire): static
    {
        $this->date_construire = $date_construire;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getMedia(): ?string
    {
        return $this->media;
    }

    public function setMedia(string $media): static
    {
        $this->media = $media;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

src/Form/AnnonceType.php
<?php

namespace App\Form;

use App\Entity\Annonce;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class AnnonceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
                    ->add('titre',TextType::class,[
            'attr'=>['class'=>'form-control mb-2','minlength'=>'2','maxlength'=>'100'],
            'label'=>'Title',
            'constraints'=>[new Assert\NotBlank(),new Assert\Length(['min'=>2,'max'=>100])]])
  
            ->add('category',TextType::class,[
            'attr'=>['class'=>'form-select mb-2','minlength'=>'2','maxlength'=>'100'
        
    ],
            'label'=>'Categorie',
            'constraints'=>[new Assert\NotBlank(),new Assert\Length(['min'=>2,'max'=>100])]])

            ->add('type',TextType::class,[
            'attr'=>['class'=>'form-select mb-2','minlength'=>'2','maxlength'=>'100'],
            'label'=>'Type',
            'constraints'=>[new Assert\NotBlank(),new Assert\Length(['min'=>2,'max'=>100])]])

            ->add('description',TextareaType::class,[
            'attr'=>['class'=>'form-control mb-2','minlength'=>'2','maxlength'=>500],
            'label'=>'Description',
            'constraints'=>[new Assert\NotBlank(),new Assert\Length(['min'=>2 ,'max'=>500])]])

            ->add('surface',NumberType::class,[
            'attr'=>['class'=>'form-control mb-2','greaterthan'=>'10'],
            'label'=>'Surface',
            'constraints'=>[new Assert\NotNull()]])

            ->add('number_rooms',IntegerType::class,[
            'attr'=>['class'=>'form-control mb-2','placeholder'=>'chambres'],
            'label'=>'Chambres',
            'constraints'=>[new Assert\NotNull()]])

            ->add('number_bathrooms',IntegerType::class,[
            'attr'=>['class'=>'form-control mb-2'],
            'label'=>'Salle de Bains',
            'constraints'=>[new Assert\NotNull()]])

            ->add('number_stages',IntegerType::class,[
            'attr'=>['class'=>'form-control mb-2'],
            'label'=>'Etages',
            'constraints'=>[new Assert\NotNull()]])

            ->add('numero_stage',IntegerType::class,[
            'attr'=>['class'=>'form-control mb-2'],
            'label'=>'N°Etage',
            'constraints'=>[new Assert\NotNull()]])

            ->add('number_parkings',IntegerType::class,[
            'attr'=>['class'=>'form-control mb-2'],
            'label'=>'Parkings',
            'constraints'=>[new Assert\NotNull()]])

            ->add('date_construire',DateTimeType::class,[
            'attr'=>['class'=>'form-control mb-2'],
            'label'=>'Date_Construire',
            'constraints'=>[new Assert\NotNull()]])

            ->add('price',NumberType::class,[
            'attr'=>['class'=>'form-control mb-2','greaterthan'=>'1'],
            'label'=>'Prix',
            'constraints'=>[new Assert\NotNull()]])

            ->add('media',FileType::class,[
            'attr'=>['class'=>'form-control mb-2','minlength'=>'2','maxlength'=>'255'],
            'label'=>'Media',
            'constraints'=>[new Assert\NotBlank(),new Assert\Length(['min'=>2,'max'=>255])]])
           
        ;
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Annonce::class,
        ]);
    }
}

src/Controller/AnnonceController.php
<?php

namespace App\Controller;

use App\Entity\Annonce;
use App\Form\AnnonceType;
use App\Repository\AnnonceRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/annonce')]
class AnnonceController extends AbstractController
{
    #[Route('/', name: 'app_annonce_index', methods: ['GET'])]
    public function index(AnnonceRepository $annonceRepository): Response
    {
        return $this->render('annonce/index.html.twig', [
            'annonces' => $annonceRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_annonce_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $annonce = new Annonce();
        $form = $this->createForm(AnnonceType::class, $annonce);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($annonce);
            $entityManager->flush();

            return $this->redirectToRoute('app_annonce_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('annonce/new.html.twig', [
            'annonce' => $annonce,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_annonce_show', methods: ['GET'])]
    public function show(Annonce $annonce): Response
    {
        return $this->render('annonce/show.html.twig', [
            'annonce' => $annonce,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_annonce_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Annonce $annonce, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AnnonceType::class, $annonce);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_annonce_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('annonce/edit.html.twig', [
            'annonce' => $annonce,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_annonce_delete', methods: ['POST'])]
    public function delete(Request $request, Annonce $annonce, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$annonce->getId(), $request->request->get('_token'))) {
            $entityManager->remove($annonce);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_annonce_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/annonce/_delete_form.html.twig
<form method="post" action="{{ path('app_annonce_delete', {'id': annonce.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ annonce.id) }}">
    <button class="btn">Delete</button>
</form>

templates/annonce/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/annonce/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Annonce{% endblock %}

{% block body %}
    <h1>Edit Annonce</h1>

    {{ include('annonce/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_annonce_index') }}">back to list</a>

    {{ include('annonce/_delete_form.html.twig') }}
{% endblock %}

templates/annonce/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonce index{% endblock %}

{% block body %}
    <h1>Annonce index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Category</th>
                <th>Type</th>
                <th>Description</th>
                <th>Surface</th>
                <th>Number_rooms</th>
                <th>Number_bathrooms</th>
                <th>Number_stages</th>
                <th>Numero_stage</th>
                <th>Number_parkings</th>
                <th>Date_construire</th>
                <th>Price</th>
                <th>Media</th>
                <th>CreatedAt</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for annonce in annonces %}
            <tr>
                <td>{{ annonce.id }}</td>
                <td>{{ annonce.titre }}</td>
                <td>{{ annonce.category }}</td>
                <td>{{ annonce.type }}</td>
                <td>{{ annonce.description }}</td>
                <td>{{ annonce.surface }}</td>
                <td>{{ annonce.numberRooms }}</td>
                <td>{{ annonce.numberBathrooms }}</td>
                <td>{{ annonce.numberStages }}</td>
                <td>{{ annonce.numeroStage }}</td>
                <td>{{ annonce.numberParkings }}</td>
                <td>{{ annonce.dateConstruire ? annonce.dateConstruire|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ annonce.price }}</td>
                <td>{{ annonce.media }}</td>
                <td>{{ annonce.createdAt ? annonce.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_annonce_show', {'id': annonce.id}) }}">show</a>
                    <a href="{{ path('app_annonce_edit', {'id': annonce.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="16">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_annonce_new') }}">Create new</a>
{% endblock %}

templates/annonce/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Annonce{% endblock %}

{% block body %}
<div class="m-5"></div>
    <h1>Create new Annonce</h1>

    {{ include('annonce/_form.html.twig') }}

    
    <a href="{{ path('app_annonce_index') }}">back to list</a>
</div>
    {% endblock %}

templates/annonce/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonce{% endblock %}

{% block body %}
    <h1>Annonce</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ annonce.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ annonce.titre }}</td>
            </tr>
            <tr>
                <th>Category</th>
                <td>{{ annonce.category }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ annonce.type }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ annonce.description }}</td>
            </tr>
            <tr>
                <th>Surface</th>
                <td>{{ annonce.surface }}</td>
            </tr>
            <tr>
                <th>Number_rooms</th>
                <td>{{ annonce.numberRooms }}</td>
            </tr>
            <tr>
                <th>Number_bathrooms</th>
                <td>{{ annonce.numberBathrooms }}</td>
            </tr>
            <tr>
                <th>Number_stages</th>
                <td>{{ annonce.numberStages }}</td>
            </tr>
            <tr>
                <th>Numero_stage</th>
                <td>{{ annonce.numeroStage }}</td>
            </tr>
            <tr>
                <th>Number_parkings</th>
                <td>{{ annonce.numberParkings }}</td>
            </tr>
            <tr>
                <th>Date_construire</th>
                <td>{{ annonce.dateConstruire ? annonce.dateConstruire|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ annonce.price }}</td>
            </tr>
            <tr>
                <th>Media</th>
                <td>{{ annonce.media }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ annonce.createdAt ? annonce.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('app_annonce_index') }}" role="button">back to list</a>
    
    <a class="btn btn-primary" href="{{ path('app_annonce_edit', {'id': annonce.id}) }}" role="button">edit</a>

    {{ include('annonce/_delete_form.html.twig') }}
{% endblock %}